### ISSUE TITLE
HHVM in Alpine

### ISSUE THREAD

**Issue by mancvso** [etopian/docker-wordpress-cli#1]
Hi buddy, I'm implementing a use case similar to you (without the CLI interface) and cannot find any way to enable HHVM inside an Alpine container.

Did you had any luck with this? Any tip?

Thanks in advance.

**Comment by etopian** [comment]
I don't think it's possible right now. Alpine uses ulibc instead of glib. But I can't find a binary anywhere which runs HHVM on Alpine, and it's most likely not possible: https://github.com/facebook/hhvm/issues/302

Try using Debian Wheezy instead, it should be smaller than Ubuntu.

**Comment by mancvso** [comment]
Alpine uses `musl libc` and `glibc` can be installed too [ref](https://github.com/frol/docker-alpine-oraclejdk8/blob/master/Dockerfile#L17) so it shouldn't be a problem.

What I can't do is static linking on the hhvm binary :(

**Comment by etopian** [comment]
Probably recommend opening an issue with Alpine or HHVM people. I don't as a rule compile my own packages because I don't have the time to maintain them. I wait for others to do that and then integrate them.

**Comment by mancvso** [comment]
I know, compiling is terrible!
But hey, great project and thank you for your time!
